name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/free_icon_cloud_7280692.png
  - assets/vectors/group_260_x2.svg
  - assets/vectors/group_1561_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/layer_1_x2.svg
  - assets/vectors/union_x2.svg
  - assets/vectors/layer_11_x2.svg
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/group_157_x2.svg
  - assets/vectors/battery_end_2_x2.svg
  - assets/vectors/icon_mobile_signal_4_x2.svg
  - assets/vectors/group_158_x2.svg
  - assets/vectors/group_1581_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/group_156_x2.svg
  - assets/vectors/layer_14_x2.svg
  - assets/vectors/group_43_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/icon_mobile_signal_6_x2.svg
  - assets/vectors/battery_end_9_x2.svg
  - assets/vectors/battery_end_5_x2.svg
  - assets/vectors/icon_mobile_signal_1_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/icon_mobile_signal_2_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/vectors/battery_end_3_x2.svg
  - assets/vectors/icon_mobile_signal_3_x2.svg
  - assets/vectors/battery_end_7_x2.svg
  - assets/vectors/wifi_8_x2.svg
  - assets/vectors/wifi_9_x2.svg
  - assets/vectors/battery_end_1_x2.svg
  - assets/vectors/icon_mobile_signal_7_x2.svg
  - assets/vectors/icon_mobile_signal_8_x2.svg
  - assets/vectors/battery_end_10_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/images/free_icon_cloud_7280692.png
  - assets/vectors/container_x2.svg
  - assets/vectors/layer_12_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/union_1_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/icon_mobile_signal_9_x2.svg
  - assets/vectors/layer_13_x2.svg
  - assets/vectors/battery_end_8_x2.svg
  - assets/vectors/icon_mobile_signal_x2.svg
  - assets/vectors/battery_end_6_x2.svg
  - assets/vectors/wifi_1_x2.svg

